export const getAppsScriptCode = (businessName: string): string => `
/**
 * ${businessName} — Lead Capture Script
 * Auto-generated by Website Builder
 * 
 * This script:
 * 1. Creates a "${businessName} Leads" spreadsheet (if it doesn't exist)
 * 2. Accepts form submissions via POST requests
 * 3. Appends lead data as new rows
 * 4. Returns lead stats via GET requests
 */

// ===== CONFIGURATION =====
const SHEET_NAME = "${businessName} Leads";
const HEADERS = ["Date", "Name", "Email", "Phone", "Message", "Service"];

// ===== MAIN FUNCTIONS =====

/**
 * Handles GET requests — returns lead stats
 */
function doGet(e) {
  try {
    const action = e.parameter.action || 'stats';
    
    if (action === 'stats') {
      return sendResponse(getLeadStats());
    }
    
    if (action === 'recent') {
      return sendResponse(getRecentLeads());
    }
    
    if (action === 'info') {
      return sendResponse(getSheetInfo());
    }
    
    return sendResponse({ error: 'Unknown action' }, 400);
  } catch (error) {
    return sendResponse({ error: error.message }, 500);
  }
}

/**
 * Handles POST requests — appends a new lead
 */
function doPost(e) {
  try {
    const data = JSON.parse(e.postData.contents);
    
    // Validate required fields
    if (!data.name || !data.email) {
      return sendResponse({ error: 'Name and email are required' }, 400);
    }
    
    const sheet = getOrCreateSheet();
    const now = new Date();
    const dateStr = Utilities.formatDate(now, Session.getScriptTimeZone(), "yyyy-MM-dd HH:mm:ss");
    
    // Append the new lead row
    sheet.appendRow([
      dateStr,
      data.name || '',
      data.email || '',
      data.phone || '',
      data.message || '',
      data.service || ''
    ]);
    
    return sendResponse({ 
      success: true, 
      message: 'Lead captured successfully',
      timestamp: dateStr
    });
  } catch (error) {
    return sendResponse({ error: error.message }, 500);
  }
}

// ===== HELPER FUNCTIONS =====

/**
 * Gets or creates the leads spreadsheet
 */
function getOrCreateSheet() {
  const files = DriveApp.getFilesByName(SHEET_NAME);
  
  if (files.hasNext()) {
    const file = files.next();
    return SpreadsheetApp.open(file).getActiveSheet();
  }
  
  // Create new spreadsheet
  const ss = SpreadsheetApp.create(SHEET_NAME);
  const sheet = ss.getActiveSheet();
  
  // Set up headers
  sheet.getRange(1, 1, 1, HEADERS.length).setValues([HEADERS]);
  
  // Format headers
  const headerRange = sheet.getRange(1, 1, 1, HEADERS.length);
  headerRange.setFontWeight("bold");
  headerRange.setBackground("#4285F4");
  headerRange.setFontColor("#FFFFFF");
  
  // Set column widths
  sheet.setColumnWidth(1, 160); // Date
  sheet.setColumnWidth(2, 150); // Name
  sheet.setColumnWidth(3, 200); // Email
  sheet.setColumnWidth(4, 130); // Phone
  sheet.setColumnWidth(5, 300); // Message
  sheet.setColumnWidth(6, 150); // Service
  
  // Freeze header row
  sheet.setFrozenRows(1);
  
  return sheet;
}

/**
 * Returns lead statistics
 */
function getLeadStats() {
  const sheet = getOrCreateSheet();
  const lastRow = sheet.getLastRow();
  const totalLeads = Math.max(0, lastRow - 1); // Subtract header row
  
  let lastLeadDate = null;
  if (totalLeads > 0) {
    lastLeadDate = sheet.getRange(lastRow, 1).getValue();
  }
  
  return {
    totalLeads: totalLeads,
    lastLeadDate: lastLeadDate ? lastLeadDate.toString() : null,
    sheetUrl: SpreadsheetApp.getActiveSpreadsheet() 
      ? SpreadsheetApp.getActiveSpreadsheet().getUrl() 
      : getSheetUrl()
  };
}

/**
 * Returns the last 5 leads
 */
function getRecentLeads() {
  const sheet = getOrCreateSheet();
  const lastRow = sheet.getLastRow();
  const totalLeads = Math.max(0, lastRow - 1);
  
  if (totalLeads === 0) {
    return { totalLeads: 0, recentLeads: [] };
  }
  
  const startRow = Math.max(2, lastRow - 4); // Last 5 rows (skip header)
  const numRows = lastRow - startRow + 1;
  const data = sheet.getRange(startRow, 1, numRows, HEADERS.length).getValues();
  
  const recentLeads = data.map(function(row) {
    return {
      date: row[0] ? row[0].toString() : '',
      name: row[1] || '',
      email: row[2] || '',
      phone: row[3] || '',
      message: row[4] || '',
      service: row[5] || ''
    };
  }).reverse(); // Most recent first
  
  return {
    totalLeads: totalLeads,
    recentLeads: recentLeads
  };
}

/**
 * Returns sheet info for connection verification
 */
function getSheetInfo() {
  const sheet = getOrCreateSheet();
  const ss = sheet.getParent();
  return {
    connected: true,
    sheetName: ss.getName(),
    sheetUrl: ss.getUrl(),
    sheetId: ss.getId()
  };
}

/**
 * Helper to get sheet URL
 */
function getSheetUrl() {
  const files = DriveApp.getFilesByName(SHEET_NAME);
  if (files.hasNext()) {
    return files.next().getUrl();
  }
  return null;
}

/**
 * CORS-enabled JSON response
 */
function sendResponse(data, statusCode) {
  return ContentService
    .createTextOutput(JSON.stringify(data))
    .setMimeType(ContentService.MimeType.JSON);
}
`;
