import { BusinessTemplate } from '../types/builder';

// Generate unique IDs
const id = () => Math.random().toString(36).slice(2, 9);

export const businessTemplates: Record<string, BusinessTemplate> = {

  barbershop: {
    type: 'barbershop',
    label: 'Barbershop',
    icon: 'Scissors',
    defaultServices: [
      { id: id(), name: 'Classic Haircut', price: '$25', description: 'Traditional cut with clippers and scissors' },
      { id: id(), name: 'Beard Trim', price: '$15', description: 'Shape and trim your beard' },
      { id: id(), name: 'Hot Towel Shave', price: '$30', description: 'Luxury straight razor shave' },
      { id: id(), name: 'Kids Haircut', price: '$18', description: 'For children under 12' },
      { id: id(), name: 'Haircut + Beard Combo', price: '$35', description: 'Full grooming package' },
    ],
    defaultFeatures: {
      booking: true,
      payments: true,
      gallery: true,
      menu: false,
      priceList: true,
      testimonials: true,
      map: true,
      socialMedia: true,
    },
    heroImageKeyword: 'barbershop interior',
    ctaText: 'Book Your Cut',
    suggestedStyles: ['bold', 'dark'],
  },

  salon: {
    type: 'salon',
    label: 'Salon / Beauty',
    icon: 'Sparkles',
    defaultServices: [
      { id: id(), name: 'Wash & Blowout', price: '$45', description: 'Shampoo, condition, and style' },
      { id: id(), name: 'Full Color', price: '$120', description: 'All-over single process color' },
      { id: id(), name: 'Highlights / Balayage', price: '$150+', description: 'Dimensional color techniques' },
      { id: id(), name: 'Manicure', price: '$30', description: 'Classic manicure with polish' },
      { id: id(), name: 'Gel Nails', price: '$50', description: 'Long-lasting gel application' },
      { id: id(), name: 'Eyebrow Wax', price: '$15', description: 'Brow shaping and cleanup' },
    ],
    defaultFeatures: {
      booking: true,
      payments: true,
      gallery: true,
      menu: false,
      priceList: true,
      testimonials: true,
      map: true,
      socialMedia: true,
    },
    heroImageKeyword: 'beauty salon',
    ctaText: 'Book an Appointment',
    suggestedStyles: ['luxury', 'modern'],
  },

  restaurant: {
    type: 'restaurant',
    label: 'Restaurant / Food',
    icon: 'Utensils',
    defaultServices: [
      { id: id(), name: 'Appetizers', category: 'Starters', description: 'Small plates to begin your meal' },
      { id: id(), name: 'Signature Burger', price: '$16', category: 'Mains', description: 'Half-pound angus with house sauce' },
      { id: id(), name: 'Grilled Salmon', price: '$24', category: 'Mains', description: 'Atlantic salmon with seasonal vegetables' },
      { id: id(), name: 'Caesar Salad', price: '$12', category: 'Salads', description: 'Romaine, croutons, parmesan' },
      { id: id(), name: 'Chocolate Lava Cake', price: '$10', category: 'Desserts', description: 'Warm chocolate center with vanilla ice cream' },
    ],
    defaultFeatures: {
      booking: true,  // reservations
      payments: false,
      gallery: true,
      menu: true,
      priceList: false,
      testimonials: true,
      map: true,
      socialMedia: true,
    },
    heroImageKeyword: 'restaurant food plating',
    ctaText: 'Make a Reservation',
    suggestedStyles: ['warm', 'modern'],
  },

  consultant: {
    type: 'consultant',
    label: 'Consultant / Coach',
    icon: 'Brain',
    defaultServices: [
      { id: id(), name: 'Discovery Call', price: 'Free', description: '30-minute intro consultation' },
      { id: id(), name: '1-on-1 Coaching Session', price: '$150/hr', description: 'Personalized coaching session' },
      { id: id(), name: 'Group Workshop', price: '$75/person', description: 'Interactive group learning' },
      { id: id(), name: 'VIP Day', price: '$997', description: 'Full-day intensive strategy session' },
      { id: id(), name: 'Monthly Coaching Package', price: '$500/mo', description: '4 sessions + email support' },
    ],
    defaultFeatures: {
      booking: true,
      payments: true,
      gallery: false,
      menu: false,
      priceList: true,
      testimonials: true,
      map: false,
      socialMedia: true,
    },
    heroImageKeyword: 'professional coaching',
    ctaText: 'Book a Discovery Call',
    suggestedStyles: ['minimal', 'modern'],
  },

  store: {
    type: 'store',
    label: 'Online Store',
    icon: 'ShoppingBag',
    defaultServices: [
      { id: id(), name: 'Featured Product 1', price: '$29.99', description: 'Your best-selling item' },
      { id: id(), name: 'Featured Product 2', price: '$49.99', description: 'Popular with customers' },
      { id: id(), name: 'Gift Bundle', price: '$79.99', description: 'Curated gift package' },
      { id: id(), name: 'New Arrival', price: '$34.99', description: 'Just dropped this week' },
    ],
    defaultFeatures: {
      booking: false,
      payments: true,
      gallery: true,
      menu: false,
      priceList: true,
      testimonials: true,
      map: false,
      socialMedia: true,
    },
    heroImageKeyword: 'small business products',
    ctaText: 'Shop Now',
    suggestedStyles: ['modern', 'minimal'],
  },

  mechanic: {
    type: 'mechanic',
    label: 'Mechanic / Auto',
    icon: 'Wrench',
    defaultServices: [
      { id: id(), name: 'Oil Change', price: '$39.99', description: 'Full synthetic oil change' },
      { id: id(), name: 'Brake Service', price: '$149+', description: 'Pads, rotors, and inspection' },
      { id: id(), name: 'Tire Rotation', price: '$29.99', description: 'Rotate and balance all 4 tires' },
      { id: id(), name: 'Engine Diagnostics', price: '$75', description: 'Full computer diagnostic scan' },
      { id: id(), name: 'AC Repair', price: '$125+', description: 'Recharge and leak repair' },
    ],
    defaultFeatures: {
      booking: true,
      payments: true,
      gallery: true,
      menu: false,
      priceList: true,
      testimonials: true,
      map: true,
      socialMedia: false,
    },
    heroImageKeyword: 'auto repair shop',
    ctaText: 'Schedule Service',
    suggestedStyles: ['bold', 'dark'],
  },

  tutor: {
    type: 'tutor',
    label: 'Tutor / Educator',
    icon: 'BookOpen',
    defaultServices: [
      { id: id(), name: 'Math Tutoring', price: '$50/hr', description: 'Algebra, geometry, calculus' },
      { id: id(), name: 'Reading & Writing', price: '$50/hr', description: 'Comprehension and essay skills' },
      { id: id(), name: 'Test Prep (SAT/ACT)', price: '$65/hr', description: 'Targeted test strategies' },
      { id: id(), name: 'Study Skills Workshop', price: '$40/hr', description: 'Organization and learning techniques' },
    ],
    defaultFeatures: {
      booking: true,
      payments: true,
      gallery: false,
      menu: false,
      priceList: true,
      testimonials: true,
      map: false,
      socialMedia: true,
    },
    heroImageKeyword: 'tutoring education',
    ctaText: 'Book a Session',
    suggestedStyles: ['warm', 'modern'],
  },

  church: {
    type: 'church',
    label: 'Church / Ministry',
    icon: 'Church',
    defaultServices: [
      { id: id(), name: 'Sunday Worship', description: 'Main service at 10:00 AM' },
      { id: id(), name: 'Bible Study', description: 'Wednesday evenings at 7:00 PM' },
      { id: id(), name: 'Youth Group', description: 'Friday nights for ages 13-18' },
      { id: id(), name: 'Community Outreach', description: 'Monthly volunteer events' },
      { id: id(), name: 'Prayer Meeting', description: 'Tuesday mornings at 6:30 AM' },
    ],
    defaultFeatures: {
      booking: false,
      payments: false,
      gallery: true,
      menu: false,
      priceList: false,
      testimonials: false,
      map: true,
      socialMedia: true,
    },
    heroImageKeyword: 'church community worship',
    ctaText: 'Join Us This Sunday',
    suggestedStyles: ['warm', 'modern'],
  },

  other: {
    type: 'other',
    label: 'Other',
    icon: 'LayoutGrid',
    defaultServices: [
      { id: id(), name: 'Service 1', price: '$0', description: 'Describe your service' },
      { id: id(), name: 'Service 2', price: '$0', description: 'Describe your service' },
    ],
    defaultFeatures: {
      booking: true,
      payments: false,
      gallery: true,
      menu: false,
      priceList: true,
      testimonials: true,
      map: true,
      socialMedia: true,
    },
    heroImageKeyword: 'small business',
    ctaText: 'Get Started',
    suggestedStyles: ['modern', 'minimal'],
  },
};
